// example/packages/vite-react/src/App.jsx
import React, { useState } from 'react'
import { Outlet, Link  } from 'react-router-dom'
import './App.css'


function App() {
  const [microName, setMicroName] = useState('vite_react')
  window.microName = 'vite_react'
  const outPut = (e) => {
    setMicroName(window.microName = e.target.value)
  }

  return (
    <div className="container">
      <h1>Vite + React</h1>
      <h3>
        设置全局变量：microName：
        <input type="text" value={microName} placeholder='设置全局变量：microName' onInput={outPut} />
      </h3>
      <button onClick={() => console.log('全局变量：microName', window.microName)}>打印全局变量：microName</button>

      <div>
        <Link to={"/"}>Go to Home</Link>
        <Link style={{marginLeft: '20px'}} to={"/about"}>Go to About</Link>
      </div>

      <Outlet></Outlet>
    </div>
  )
}

export default App

// example/packages/vite-vue2/src/App.vue
<template>
  <div class="container">
    <h1>vue2 + vite</h1>
    <h3>
        设置全局变量：microName：
        <input type="text" v-model='microName' placeholder='设置全局变量：microName' @input='setMicroName' />
        <button @click='output'>打印全局变量：microName</button>
    </h3>

    <div style="margin-bottom: 20px">
      <router-link to="/">Go to Home</router-link>
      <router-link style="margin-left: 20px" to="/about">Go to About</router-link>
    </div>

    <router-view></router-view>
  </div>
</template>

<script>
window.microName = 'vite_vue2'
export default {
  data() {
    return {
      microName: 'vite_vue2'
    }
  },
  methods: {
    setMicroName() {
      window.microName = this.microName
    },
    output() {
      console.log('全局变量：microName', window.microName)
    }
  }
}
</script>

<style>

.container {
  color: blue;
  border: 1px solid;
}




















</style>
